##############################################################################
# Copyright 2021 IBM Corp. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################
############################################################################
# Option 1: New Copy CICS programs using MVS operator command  
# Comment the following piece of code if using z/OS CICS collection for 
# New copy
############################################################################  
- name: New Copy CICS Program using zos_operator
  zos_operator:
    cmd: 'F CICSTS55,CEMT S PROG({{ item }}) NEW'
  loop: "{{ cics_pgms }}"
  register: result
  
############################################################################
# Option 2: New Copy CICS programs using z/OS CICS collection  
# Uncomment the following piece of code if using z/OS CICS collection for 
# New copy. CMCI should be enabled for this. The CMCI variables should be
# set in ./group_vars/all.yml
############################################################################  
#- name: New Copy CICS Program using zos_cics
#  delegate_to: localhost
#  cmci_action:
#    context: '{{ context }}'
#    scope: '{{ scope }}'
#    cmci_host: '{{ cmci_host }}'
#    cmci_port: '{{ cmci_port | int }}'
#    scheme: '{{ scheme }}'
#    action_name: NEWCOPY
#    type: CICSProgram
#    resources:
#      filter:
#        program: '{{ item }}'
#  loop: "{{ cics_pgms }}"
#  register: result  

- name: Response for New Copy
  debug:
    msg: "{{ result }}"