##############################################################################
# Copyright 2021 IBM Corp. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##############################################################################
- name: Job template render for LOAD module copy
  template:
    src: './files/LOADCOPY.j2'
    dest: '/tmp/LOADCOPY.bin'
  register: result

- name: LOAD module copy - Template Response
  debug:
    msg: "{{ result }}"
       
- name: Convert LOAD Copy JCL encoding from ISO8859-1 to IBM-1047
  zos_encode:
    src: '/tmp/LOADCOPY.bin'
    dest: '/tmp/LOADCOPY.jcl'
    to_encoding: IBM-1047
    from_encoding: ISO8859-1
  register: result

- name: LOAD Copy JCL Encoding conversion response
  debug:
    msg: "{{ result }}"   

- name: Submit the job from USS
  zos_job_submit:
    src: '/tmp/LOADCOPY.jcl'
    location: USS
    wait: true
  register: result

- name: Job Response
  debug:
    msg: "{{ result.jobs[0].ret_code }}"